services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: new-portfolio:dev
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
